config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: [:new]
  end
  resources :comments, only: [:create]
  root "subs#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
validates :content, :author, :post, presence: true

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :author_id, presence: true
  # validates :post_subs, presence: true

  has_many :post_subs, inverse_of: :post
  has_many :subs, through: :post_subs
  has_many :comments

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: "User"

end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post, :sub, presence: true

  belongs_to :sub, inverse_of: :post_subs
  belongs_to :post, inverse_of: :post_subs

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator_id, presence: true
  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: "User"

    has_many :post_subs, inverse_of: :sub
    has_many :posts, through: :post_subs
end

app/models/user.rb
class User < ActiveRecord::Base

  after_initialize :ensure_session_token

  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  attr_reader :password

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(32)
    self.save!
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(32)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return nil unless @user
    @user.is_password?(password) ? @user : nil
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    current_user ||= User.find_by_session_token(session[:session_token])
    current_user.nil? ? nil : current_user
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_no_user!
  end

  def require_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    parent_post = @comment.post
    @comment.author = current_user
    if @comment.save
      redirect_to post_url(parent_post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def new
    @comment = Comment.new
    render :new
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    # @post.sub_id =
    if @post.save
      redirect_to root_url
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    render :new
  end

  def show
    @post = Post.find_by_id(params[:id])
    @author = @post.author
    render :show
  end

  def edit
    @post = Post.find_by_id(params[:id])
    render :edit
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    current_sub = @post.subs
    @post.destroy
    redirect_to subs_url(current_sub)
  end


  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [] )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "bad login information"
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
    @subs = Sub.all
    render :index
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def new
    @sub = Sub.new
    render :new
  end

  def show
    @sub = Sub.find_by_id(params[:id])
    @moderator = @sub.moderator
  end

  def edit
    @sub = Sub.find_by(params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      # fail
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  def show
    @user = User.find_by(params[:id])
  end

  def edit
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Write Comment</h1>


<form action= "<%= comments_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Comment: <textarea name="comment[content]" rows="8" cols="40"></textarea>
  </label>

  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id]  %>">
  <input type="submit" value="Submit">

</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <nav>
      <% if logged_in? %>
        <%= button_to("Logout", session_url, method: :delete) %>
        <%= button_to("Home", subs_url, method: :get) %>
        <%= button_to("My SubReddits", user_url(current_user), method: :get) %>
        <%= button_to "Submit Post", new_post_url, method: :get %>
      <% else %>
        <%= button_to("Login", new_session_url, method: :get) %>
        <%= button_to("Sign Up", new_user_url, method: :get) %>
      <% end %>
        <%= button_to "Create Sub", new_sub_url, method: :get %>
      <% if flash[:errors] %>
        <% flash[:errors].each do |e| %>
         <%= e %>
        <% end %>
      <% end %>
    </nav>
  </header>


<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>

<form action= "<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title: <input type="text" name="post[title]" value=" <%= @post.title %>">
  </label>
  <label>
    Description: <textarea name="post[content]" rows="8" cols="40">
      <%= @post.content%></textarea>
  </label>
  <label>
    Url:  <input type="text" name="post[url]" value=" <%= @post.url %> ">
  </label>

  <% Sub.all.each do |sub| %>

    <label>
      <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
        <%= sub.title  %>
    </label>

    <% end %>

  <input type="submit" value="Submit">

</form>

app/views/posts/new.html.erb
<h1>Submit a new post</h1>

<form action= "<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title: <input type="text" name="post[title]" value="">
  </label>
  <label>
    Description: <textarea name="post[content]" rows="8" cols="40"></textarea>
  </label>
  <label>
    Url:  <input type="text" name="post[url]" value="">
  </label>

  <% Sub.all.each do |sub| %>

    <label>
      <input type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
        <%= sub.title  %>
    </label>

    <% end %>

  <input type="submit" value="Submit">

</form>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p>
  http://<%= @post.url %>.com
</p>
<p>
Body: <%= @post.content %>
</p>

<p>
  <% @post.comments.each do |c| %>
    <%= c.content %>
  <% end %>
</p>
<p>
  <%= button_to "Write Comment", new_post_comment_url(@post), method: :get %>
</p>

<% if current_user == @author %>
  <%= button_to "Edit", edit_post_url, method: :get %>
<% end %>

app/views/subs/edit.html.erb
<h1>Edit you sub</h1>

<form action= "<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
   <input type="hidden" name="_method" value="PATCH">
  <label>
    Title: <input type="text" name="sub[title]" value=" <%= @sub.title %>">
  </label>
  <label>
    Description: <textarea name="sub[description]" rows="8" cols="40"> <%= @sub.description %> </textarea>
  </label>
  <input type="submit" value="Submit">
</form>

app/views/subs/index.html.erb
<h1>Welcome to RedditClone</h1>
<ul>
<% @subs.each do |sub| %>
  <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create A New SubReddit</h1>

<form action= "<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title: <input type="text" name="sub[title]" value="">
  </label>
  <label>
    Description: <textarea name="sub[description]" rows="8" cols="40"></textarea>
  </label>
  <input type="submit" value="Submit">
</form>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<p>
  About: <%= @sub.description %>
</p>
<p>
  Mod: <%= @moderator.username %>
</p>

<ul>
  <% @sub.posts.each do |post| %>
  <li><%= link_to post.title, post_url(post) %> </li>
    <% if current_user == @moderator %>
      <%= button_to "Delete Post", post_url(post), method: :delete %>
    <% end %>
  <% end %>
</ul>

<% if current_user == @moderator %>
  <%= button_to "Edit", edit_sub_url, method: :get %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Username:
    <input type="text" name="user[username]">
  </label>
  <label>
    Password:
    <input type="password" name="user[password]">
  </label>
  <input type="submit" value="Go!!!">
</form>

app/views/users/show.html.erb
<h1>Your Profile</h1>

<h2>Hello, <%= current_user.username %></h2>

<h3>Subs you moderate</h3>
  <ul>
    <% current_user.subs.each do |sub| %>
    <li> <%= link_to sub.title, sub_url(sub) %> </li>
    <% end %>
  </ul>